name: Test DB Connection (.NET Framework)

on:
  workflow_dispatch:  # Run manually

jobs:
  test-db:
    runs-on: windows-latest  #  Must use Windows runner for .NET Framework

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 1: Setup NuGet CLI
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # Step 2: Restore packages (for packages.config-based project)
      - name: Restore NuGet Packages
        run: nuget restore DevOps_FlyWay/DevOps_FlyWay.csproj

      # Step 3: Setup MSBuild (needed for .NET Framework builds)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Step 4: Build the project
      - name: Build
        run: msbuild DevOps_FlyWay/DevOps_FlyWay.csproj /p:Configuration=Release

      # Step 5: Run your console app to test DB connection
      - name: Run DB Test App
        working-directory: DevOps_FlyWay/bin/Release
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: DevOps_FlyWay.exe
