name: Test Database Connection (.NET Console App)

on:
  workflow_dispatch:

jobs:
  test-db:
    runs-on: windows-latest  #  Important: use Windows runner for .NET Framework projects

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Add NuGet setup
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # Restore NuGet packages (for packages.config projects)
      - name: Restore NuGet Packages
        run: nuget restore DevOps_FlyWay/DevOps_FlyWay.csproj

      # Setup .NET SDK (for build)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Build project
      - name: Build
        run: dotnet build DevOps_FlyWay/DevOps_FlyWay.csproj --configuration Release --no-restore

      # Run your console app
      - name: Run Console App to Test DB Connection
        working-directory: DevOps_FlyWay
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: dotnet run --configuration Release
