name: Test DB Connection (.NET Framework)

on:
  workflow_dispatch:

jobs:
  test-db:
    runs-on: windows-latest  # ✅ Required for .NET Framework

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup NuGet CLI (to restore old-style packages.config)
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # 3️⃣ Restore packages (for net462 projects)
      - name: Restore NuGet Packages
        run: nuget restore DevOps_FlyWay/DevOps_FlyWay.csproj

      # 4️⃣ Setup MSBuild (instead of dotnet)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 5️⃣ Build your project using MSBuild (not dotnet)
      - name: Build
        run: msbuild DevOps_FlyWay/DevOps_FlyWay.csproj /p:Configuration=Release

      # 6️⃣ Run your console app to test DB connection
      - name: Run DB Test App
        working-directory: DevOps_FlyWay/bin/Release
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: DevOps_FlyWay.exe
